version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
#    image: rabbitmq:3.12.1-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
